services:
  - type: web
    name: interview-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SECRET_KEY
        generateValue: true
